### ISSUE TITLE
add condition id and wind direction/speed to api $struct

### ISSUE THREAD

**Issue by bronz3beard** [dnsimmons/openweather#10]
hi Dave,

Thanks for creating this neat tidy composer package. I have really enjoyed using it.

I have been using OpenWeather together with [symbol font for Open Weather Map API](https://websygen.github.io/owfont/) and for the icons to work I need the **condition.id**, aka ``` $struct['weather'][0]['id'] ```  currently it is not apart of the data structure.

Also I need display wind speed and heading.

I have made the adjustments locally and I have them working locally, so I am happy to make a PR for you to review.
If you don't want to make changes to current structure all good I get it, I can maintain locally.

examples:

Icon usage with condition.id

``` `owf owf-${item.condition.id} owf-5x` ```

Additions to data structure 
```php
            $current['wind'] = [
                'speed' => $struct['wind']['speed'],
                'deg' => $struct['wind']['deg'],
            ];
-----------------------------------
            'wind' => [
                'speed' => $item['wind']['speed'],
                'deg' => $item['wind']['deg'],
            ],
```
&

```php
            $current['condition'] = [
                'id' => $struct['weather'][0]['id'],
                'name' => $struct['current']['weather'][0]['main'],
                'desc' => $struct['current']['weather'][0]['description'],
                'icon' => $this->api_endpoint_icons . $struct['current']['weather'][0]['icon'] . '.png',
            ];
```

**Comment by dnsimmons** [comment]
Thanks, I will take a look at this and implement in the package. Shouldn't take too long.

**Comment by dnsimmons** [comment]
I have implemented the requested changes across all of the packages methods and updated the documentation. Enjoy!

**Comment by dnsimmons** [comment]
A further update ... v 1.0.6 also exposes the cardinal wind direction now .... N, S, E, W, ...
Enjoy!
