### ISSUE TITLE
Possibility to change icons filetype to SVG

### ISSUE THREAD

**Issue by StanMenten99** [dnsimmons/openweather#13]
Hi,

I'm currently creating a new website with this package, but for this project I need to use animated svg icons.
The way as it is now, only .png files are 'allowed'.

Can you maybe adjust this?

**Comment by dnsimmons** [comment]
The URLs for the images are from the actual OpenWeather API. For example:

[icon] => https://openweathermap.org/img/w/10d.png

The package itself has no control over these URLs.

**Comment by StanMenten99** [comment]
Yes, I know that already.
But only whatever is before the iconname itself.

In your code you have hardcoded the .png filetype to it. (See line 143 on ``/src/OpenWeather.php``)
And that's what I need to change.

**Comment by dnsimmons** [comment]
Confused ... the API doesnt have SVG icon URLs so changing it wont help resolve to SVGs.

**Comment by StanMenten99** [comment]
You have the option to change the icon endpoint through the config file, right?
So, in there I've setup my own provider for the svg icons.

```'api_endpoint_icons'    => '/img/weather_icons/',```
So this resolves ``[icon] => /img/weather_icons/10d.png`` for example.

But the part .png is hardcoded, so ofourse it wouldn't work.

**Comment by dnsimmons** [comment]
If your intent is to change the config value for the icon endpoint to use a custom URL then you could just str_replace() the .png to .svg in your code. Ill take a look at this for next release but for immediate fix I would do the replace.

**Comment by dnsimmons** [comment]
just pushed the requested changes ... config file now allows you to specify extension.

**Comment by StanMenten99** [comment]
Hi, can you create a new release so I can pull the latest changes through Composer?

**Comment by dnsimmons** [comment]
1.0.7 released.
