### ISSUE TITLE
Weather maps support

### ISSUE THREAD

**Issue by Dontorpedo** [dnsimmons/openweather#3]
Hi,

nice package, weather maps support would be also great !

thanks
D

**Comment by janbildsoehansen** [comment]
yaa weather maps support would be mega nice 👍

**Comment by dnsimmons** [comment]
Not a bad idea. Ill look into it and add the support for them soon.

**Comment by janbildsoehansen** [comment]
Nice 👍

**Comment by dnsimmons** [comment]
After research ending up discovering that the 2.0 maps API support will not be free.
In the meantime  you can fetch a map layer PNG from the 1.0 API which is still available and free at the moment.

https://tile.openweathermap.org/map/{layer}/{z}/{x}/{y}.png?appid={API key}

**Comment by janbildsoehansen** [comment]
are you make a project with the 1.0 API..?

**Comment by dnsimmons** [comment]
Probably not in this case because they will be deprecating 1.0. 
1.0 Map images can be  easily fetched though ...

https://tile.openweathermap.org/map/{layer}/{z}/{x}/{y}.png?appid={API key}
