### ISSUE TITLE
OpenWhether API Update

### ISSUE THREAD

**Issue by jny986** [dnsimmons/openweather#6]
There has been an update to the master branch for the change of the API to use "exclude" instead of "part" however there has not been a release and so this breaks the functionality of the package unless installed from master.

Can you please release new version of this package to include the latest changes

**Comment by dnsimmons** [comment]
Sorry, I am not sure I understand the issue. I have done a test install and everything appears to be fine. Could you please try and explain further?

**Comment by dnsimmons** [comment]
Created a new release for version 1.0.3 containing the exclude fixes. Let me know if any issues thanks.

**Comment by jny986** [comment]
@dnsimmons This has fixed the issue. 
Thanks for the great package and for the quick reply
